#include <errno.h>  /* for perror */
#include <signal.h> /* for signal(2) kill(2) */
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/ipc.h>   /* for shmget() shmctl() */
#include <sys/shm.h>   /* for shmget() shmctl() */
#include <sys/types.h> /* for wait() kill(2)*/
#include <sys/wait.h>  /* for wait() */
#include <time.h>
#include <unistd.h> /* for fork() */

#define SHARED_FILE "./"

typedef void (*sighandler_t)(int);  // define the sighandler_t type

typedef struct att {
  int roll; /* The roll number of the student giving the attendance */

  time_t
      tm; /* To keep the time when attendance was given by the student. Read the
             manual for time(), that is, "man 2 time" Also see the manual
             entries mentioned in the "see also" section of this manual page! */
} att;

int shmid;

/**
 * @brief Allocates the memory. Also handles the error if the memory is not
 * allocated.
 *
 * @param memory_size Size needed for shared memory
 * @return int Shared memory id
 */
int getSHM(size_t memory_size) {
  int shmkey = ftok(SHARED_FILE, 1);
  int shmid = shmget(shmkey, memory_size, IPC_CREAT | 0777);

  if (shmid == -1) { /* shmget() failed() */
    perror("shmget() failed: ");
    exit(1);
  }
  return shmid;
}

/**
 * @brief Get the ptr to shared memory
 *
 * @param shmid Shared memory id
 * @return void* Pointer to shared memory
 */
void *getPtrSHM(int shmid) {
  void *value;
  value = shmat(shmid, NULL, 0);
  if (value == (void *)-1) { /* shmat fails */
    perror("shmat() failed");
    exit(1);
  }
  return value;
}

time_t getCurrentTime() {
  time_t rawtime;
  time(&rawtime);
  return rawtime;
}

int main(int argc, const char *argv[]) {
  if (argc == 1 || argc > 2) {
    printf("Usage: ./student.out <roll_number>\n");
    exit(1);
  }

  int roll_number = atoi(argv[1]);

  shmid = getSHM(sizeof(att));

  att *attendance = (att *)getPtrSHM(shmid);
  while (true) {
    if (attendance->roll == -1) {
      printf("Attendance given by: \n");
      printf("Roll number: %d\n", roll_number);
      attendance->roll = roll_number;
      attendance->tm = getCurrentTime();
      printf("Time: %s\n", ctime(&attendance->tm));
      exit(EXIT_SUCCESS);
    }
  }
  exit(EXIT_SUCCESS);
}
/*
sleep and wait are two different system calls in Unix-like operating systems that serve different purposes.

sleep is a function that suspends the execution of a process for a specified amount of time. The sleep function takes a single argument, which is the number of seconds the process should be suspended. During this time, the process is not executing and is not consuming CPU resources.

On the other hand, wait is a function that waits for a child process to terminate. The wait function takes no arguments and blocks the calling process until one of its child processes terminates. The wait function returns the process ID of the terminated child process. This is useful for parent processes that need to wait for their child processes to complete before proceeding with other tasks.

In summary, sleep is used to temporarily suspend the execution of a process, while wait is used to wait for a child process to terminate.

*/

/*
ftok is a function that generates a key for use with shmget. The first argument to ftok is a pathname, which can be any file that exists on the file system. The second argument is a project identifier, which is an integer used to distinguish between different shared memory segments. In this case, projid is set to 1.

shmget is the function used to get a shared memory segment. It takes three arguments: a key generated by ftok, the size of the shared memory segment, and a set of flags. The size of the shared memory segment is specified by n * sizeof(att), where n is a value defined elsewhere in the code and att is a data structure. The flags IPC_CREAT and 0666 are used to specify that the shared memory segment should be created if it doesn't already exist, and to set the permissions on the segment to allow read and write access by any user.

The return value of shmget is stored in the variable shmid, which is the shared memory identifier and can be used to access the shared memory segment in other parts of the code.

*/